Imported Upstream version 1.0.1a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,6 +33,7 @@ else
 fi
 
 libdir=""
+libexecdir=""
 datadir=""
 localedir=""
 mandir=""
@@ -46,6 +47,8 @@ userPrefix="$HOME/.local"
 enable_pkcs11=""
 optional_pkcs11="0"
 pkcs11Module="/usr/$multilib/opensc-pkcs11.so"
+
+gtkversion="auto"
 
 error=""
 
@@ -69,6 +72,7 @@ Options:
     --exec-prefix=PATH    Sets the installation prefix for executable files.
                           The default is to use the same prefix for all files.
     --libdir=PATH         Sets the directory for libraries. [EPREFIX/$multilib]
+    --libexecdir=PATH     Sets the directory for internal executables. [LIBDIR]
     --datadir=PATH        Sets the directory for architecture-independent
                           data. [PREFIX/share]
     --localedir=PATH      Sets the directory for translations [DATADIR/locale]
@@ -80,6 +84,7 @@ Options:
     --disable-pkcs11      Disable building PKCS#11 smartcard support
     --enable-pkcs11       Force building PKCS#11 smartcard support
     --optional-pkcs11     Detect PKCS#11 module availability at runtime
+    --with-gtk=VERSION    Selects between GTK version 2 and 3.
     --current-user        Selects a per-user installation. Equivalent to:
                               --prefix=$userPrefix
                               --plugin-path=$userPluginPath
@@ -95,6 +100,9 @@ Options:
         ;;
     --libdir=*)
         libdir=${flag#--libdir=}
+        ;;
+    --libexecdir=*)
+        libexecdir=${flag#--libexecdir=}
         ;;
     --datadir=*)
         datadir=${flag#--datadir=}
@@ -122,7 +130,7 @@ Options:
         # Deprecated alias for --pkcs11-module
         pkcs11Module=${flag#--pkcs11-engine=}
         ;;
-    --disable-pkcs11)
+    --disable-pkcs11|--enable-pkcs11=no)
         enable_pkcs11="0"
         ;;
     --enable-pkcs11)
@@ -130,6 +138,13 @@ Options:
         ;;
     --optional-pkcs11)
         optional_pkcs11="1"
+        ;;
+    --with-gtk=*)
+        gtkversion=${flag#--with-gtk=}
+        if [ "x$gtkversion" != xauto -a "x$gtkversion" != x2 -a "x$gtkversion" != x3 ]; then
+            echo "Invalid GTK version: $flag. Must be 2, 3 or auto."
+            error=1
+        fi
         ;;
     --current-user)
         if [ -z "$prefixSet" ]; then
@@ -155,6 +170,18 @@ Options:
         shift 2
         [ ! -h "$link" ] || [ "`readlink "$link"`" != "$target" ] || rm -f "$link"
         exit 0
+        ;;
+    # Some tools (e.g. Debian package tools) expect "configure" to be a
+    # true autoconf script and implement its options. These options are safely
+    # ignored by this build system.
+    --disable-dependency-tracking)
+        # Dependencies are hard-coded in the Makefile anyway
+        ;;
+    --disable-maintainer-mode|--enable-maintainer-mode)
+        # No files are written to except common/config.h
+        ;;
+    --bindir=*|--includedir=*|--infodir=*|--localstatedir=*|--oldincludedir=*|--sbindir=*|--sharedstatedir=*|--sysconfdir=*|--htmldir=*|--dvidir=*|--pdfdir=*|--psdir=*)
+        # These are standard GNU directory options. They are not used by FriBID
         ;;
     *)
         echo "Invalid option: $flag"
@@ -191,6 +218,10 @@ fi
 ### Specific directories
 if [ -z "$libdir" ]; then
     libdir="$execPath/$multilib"
+fi
+
+if [ -z "$libexecdir" ]; then
+    libexecdir="$libdir"
 fi
 
 if [ -z "$datadir" ]; then
@@ -232,9 +263,32 @@ if [ -z "$enable_pkcs11" ] && pkg-config --exists libp11; then
     enable_pkcs11=1
 fi
 
-# Check that the PKCS#11 module exists
+### Detect GTK version
+if [ $gtkversion = auto ]; then
+    if pkg-config --exists "gtk+-3.0"; then
+        gtkversion=3
+    else
+        gtkversion=2
+    fi
+fi
+
+echo "    GTK version:       $gtkversion"
+if [ $gtkversion = 2 ]; then
+    with_gtk2=1
+    with_gtk3=0
+else
+    with_gtk2=0
+    with_gtk3=1
+fi
+echo
+
+### Check that the PKCS#11 module exists
 depError=""
-pkgconfigDeps="gtk+-2.0 >= 2.12;gdk-2.0;glib-2.0;libcrypto;x11"
+if [ $with_gtk3 = 1 ]; then
+    pkgconfigDeps="gtk+-3.0;glib-2.0;libcrypto;x11"
+else
+    pkgconfigDeps="gtk+-2.0 >= 2.12;gdk-2.0;glib-2.0;libcrypto;x11"
+fi
 if [ "$enable_pkcs11" = 1 ]; then
     if [ "$optional_pkcs11" = 0 ]; then
         echo "    PKCS#11 smartcard support enabled"
@@ -251,8 +305,20 @@ if [ "$enable_pkcs11" = 1 ]; then
             depError=1
             errorType="ERROR"
         fi
-        echo
+        echo >&2
         echo "$errorType: PKCS#11 module not found" >&2
+        
+        if [ "x${pkcs11Module%opensc-pkcs11.so}" != "x$pkcs11Module" ]; then
+            echo "Make sure that you have installed OpenSC!" >&2
+        fi
+    elif type readelf grep > /dev/null 2> /dev/null && \
+	 echo 'A_a' | grep -q 'B_b\|A_a'; then
+        # Check that it's actually a PKCS#11 module
+        if ! readelf -s "$pkcs11Module" | grep -q 'C_Initialize\|C_GetFunctionList'; then
+            echo >&2
+            echo "ERROR: $pkcs11Module is not a PKCS#11 module" >&2
+            echo "Normally you should use the file opensc-pkcs11.so from OpenSC." >&2
+        fi
     fi
 else
     echo "    PKCS#11 smartcard support disabled"
@@ -295,15 +361,16 @@ cat <<EOT >"$CONFFILE"
 /* This file is automatically generated.
    Run the configure script to change the configuration. */
 
-#define CONFIGVERSION 2
+#define CONFIGVERSION 3
 
 #define PREFIX "$prefixPath"
 #define EPREFIX "$execPath"
 
-#define LIBDIR    "$libdir"
-#define DATADIR   "$datadir"
-#define LOCALEDIR "$localedir"
-#define MANDIR    "$mandir"
+#define LIBDIR     "$libdir"
+#define LIBEXECDIR "$libexecdir"
+#define DATADIR    "$datadir"
+#define LOCALEDIR  "$localedir"
+#define MANDIR     "$mandir"
 
 #define NPAPI_PLUGIN_PATHS "$pluginPaths"
 
@@ -311,6 +378,8 @@ cat <<EOT >"$CONFFILE"
 
 #define ENABLE_PKCS11 ${enable_pkcs11:-0}
 #define OPTIONAL_PKCS11 ${optional_pkcs11:-0}
+#define WITH_GTK2 ${with_gtk2}
+#define WITH_GTK3 ${with_gtk3}
 EOT
 
 ### Display success message
